stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: full

.setup_rust: &setup_rust |
  rustup component add clippy
  rustup component add rustfmt

rust_precheck:
  stage: build
  tags:
    - rust:latest
  only:
    - merge_requests
  script:
    - *setup_rust
    - cargo clippy
    - cargo fmt -- --check
    - cargo doc

test_dockertest:
  stage: test
  tags:
    - dockertest
  only:
    - merge_requests
  script:
    - export DOCKERTEST_BUILD_TEST_IMAGES=1
    - export DOCKERTEST_CONTAINER_ID_INJECT_TO_NETWORK=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
    - cargo test --verbose
