stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: full

rust_precheck:
  image: registry.gitlab.com/orcalabs/devops/rust-stable-runner:latest
  stage: build
  tags:
    - rust:latest
  only:
    - merge_requests
  script:
    - cargo clippy
    - cargo fmt -- --check
    - cargo doc --no-deps

test_dockertest:
  image: registry.gitlab.com/orcalabs/devops/rust-stable-runner:latest
  stage: test
  tags:
    - rust:latest
  only:
    - merge_requests
  script:
    - export DOCKERTEST_BUILD_TEST_IMAGES=1
    - export DOCKERTEST_CONTAINER_ID_INJECT_TO_NETWORK=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
    - cargo test --verbose -- --test-threads=1
