stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: full

.setup_rust: &setup_rust |
  rustup component add clippy
  rustup component add rustfmt
  cargo install cargo-deadlinks

rust_precheck:
  stage: build
  tags:
    - rust:latest
  only:
    - merge_requests
  script:
    - *setup_rust
    - cargo clippy
    - cargo fmt -- --check
    - cargo doc
    - cargo deadlinks

test_dockertest:
  stage: test
  tags:
    - dockertest
  only:
    - merge_requests
  script:
    - cargo test --verbose -- --test-threads=1
