[package]
name = "dockertest"
version = "0.1.3-alpha.0"
authors = ["Vegard Sandengen <vegard@orcalabs.no>", "Jon Foss Mikalsen <jon@orcalabs.no>"]
edition = "2018"
license = "MIT"
description = "A library to control docker containers when running your integration tests."
homepage = "https://www.orcalabs.no"
repository = "https://gitlab.com/orcalabs/public/dockertest-rs"
keywords = ["docker", "integration", "test", "container"]
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
documentation = "https://docs.rs/dockertest"

[dependencies]
anyhow = "1.0.30"
async-trait = "0.1.31"
bollard = "0.5.1"
dyn-clone = "1.0"
futures = "0.3.5"
serde_json = "1.0"
thiserror = "1.0.17"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1.13"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
rand = "0.7.3"

[dev-dependencies]
access-queue = "1.1"
diesel = { version = "1.0", features = ["postgres"] }
once_cell = "1.4"
test-env-log = { version = "0.2", default-features = false, features = ["trace"] }

[build-dependencies]
anyhow = "1.0.30"
