[package]
name = "dockertest"
version = "0.0.1"
authors = ["Vegard Sandengen <vegard@orcalabs.no", "Jon Foss Mikalsen <jon@orcalabs.no>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
tokio = "0.1.15"
shiplift = "0.4.0"
failure = "0.1.5"
rand = "0.6.5"
